name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint test
        run: pnpm lint
