name: Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
